// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcqdvg4rxodJaO6UDRpCJHpvq_mWPgmqw',
    appId: '1:191907012773:web:425fd99685a4e0870fed4c',
    messagingSenderId: '191907012773',
    projectId: 'se380-spring25',
    authDomain: 'se380-spring25.firebaseapp.com',
    storageBucket: 'se380-spring25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBINeJsMPlPi7M13Z8P-mX2R9Oke-zwuv8',
    appId: '1:191907012773:android:c27e4113ae94a7070fed4c',
    messagingSenderId: '191907012773',
    projectId: 'se380-spring25',
    storageBucket: 'se380-spring25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdpUWF6budyEy0SND6qyNFyjqyLRWjuZA',
    appId: '1:191907012773:ios:c00a272d7b75ec620fed4c',
    messagingSenderId: '191907012773',
    projectId: 'se380-spring25',
    storageBucket: 'se380-spring25.firebasestorage.app',
    iosClientId: '191907012773-dl34gg31mlpjiasj9emkbgn0019i4i1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.se380spring25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdpUWF6budyEy0SND6qyNFyjqyLRWjuZA',
    appId: '1:191907012773:ios:c00a272d7b75ec620fed4c',
    messagingSenderId: '191907012773',
    projectId: 'se380-spring25',
    storageBucket: 'se380-spring25.firebasestorage.app',
    iosClientId: '191907012773-dl34gg31mlpjiasj9emkbgn0019i4i1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.se380spring25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcqdvg4rxodJaO6UDRpCJHpvq_mWPgmqw',
    appId: '1:191907012773:web:655cb90b162a486f0fed4c',
    messagingSenderId: '191907012773',
    projectId: 'se380-spring25',
    authDomain: 'se380-spring25.firebaseapp.com',
    storageBucket: 'se380-spring25.firebasestorage.app',
  );

}